const fs = require("fs");
const path = require("path");
const { spawn } = require("child_process");
const sqlite3 = require("sqlite3").verbose();

function openDatabase(dbPath) {
  return new Promise((resolve, reject) => {
    const db = new sqlite3.Database(dbPath, (error) => {
      if (error) {
        reject(error);
        return;
      }

      resolve(db);
    });
  });
}

function dbRun(db, sql, params = []) {
  return new Promise((resolve, reject) => {
    db.run(sql, params, function onRun(error) {
      if (error) {
        reject(error);
        return;
      }

      resolve({
        changes: this.changes,
        lastID: this.lastID,
      });
    });
  });
}

function dbExec(db, sql) {
  return new Promise((resolve, reject) => {
    db.exec(sql, (error) => {
      if (error) {
        reject(error);
        return;
      }

      resolve();
    });
  });
}

function dbAll(db, sql, params = []) {
  return new Promise((resolve, reject) => {
    db.all(sql, params, (error, rows) => {
      if (error) {
        reject(error);
        return;
      }

      resolve(rows || []);
    });
  });
}

function closeDatabase(db) {
  return new Promise((resolve, reject) => {
    db.close((error) => {
      if (error) {
        reject(error);
        return;
      }

      resolve();
    });
  });
}

function buildExpressAppFiles(appName) {
  return {
    ".gitignore": "node_modules/\n.env\n",
    "README.md": `# ${appName}\n\nSmall Express scaffold generated by Els.\n\n## Run\n\nnpm install\nnpm start\n`,
    "app.js": `const express = require("express");
const path = require("path");
const registerIndexRoute = require("./routes/index");

const app = express();
const port = process.env.PORT || 3000;

app.set("view engine", "ejs");
app.set("views", path.join(__dirname, "views"));
app.use(express.static(path.join(__dirname, "public")));

app.get("/", (_req, res) => {
  res.render("index", { title: "${appName}" });
});

registerIndexRoute(app);

app.listen(port, () => {
  console.log("${appName} listening on http://localhost:" + port);
});
`,
    "package.json": `${JSON.stringify(
      {
        name: appName,
        version: "1.0.0",
        private: true,
        main: "app.js",
        scripts: {
          start: "node app.js",
        },
        dependencies: {
          ejs: "^3.1.10",
          express: "^4.21.2",
        },
      },
      null,
      2
    )}\n`,
    "public/styles.css": `body {
  font-family: Georgia, "Times New Roman", serif;
  margin: 0;
  min-height: 100vh;
  display: grid;
  place-items: center;
  background:
    radial-gradient(circle at top, #f0c987 0%, transparent 40%),
    linear-gradient(135deg, #f7f0e3 0%, #d8efe5 100%);
  color: #183a33;
}

main {
  width: min(720px, calc(100vw - 3rem));
  padding: 3rem;
  border-radius: 28px;
  background: rgba(255, 252, 246, 0.92);
  box-shadow: 0 18px 55px rgba(24, 58, 51, 0.12);
}

h1 {
  margin-top: 0;
  font-size: clamp(2.25rem, 5vw, 4rem);
}

p {
  line-height: 1.6;
}
`,
    "routes/index.js": `module.exports = function registerIndexRoute(app) {
  app.get("/health", (_req, res) => {
    res.json({ status: "ok" });
  });
};
`,
    "views/index.ejs": `<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title><%= title %></title>
    <link rel="stylesheet" href="/styles.css" />
  </head>
  <body>
    <main>
      <p>Generated by Els</p>
      <h1><%= title %></h1>
      <p>Your Express scaffold is ready. Add routes, APIs, and templates from here.</p>
    </main>
  </body>
</html>
`,
  };
}

async function createExpressApp({ args, cwd }) {
  const appName = args.appName;
  const targetDirectory = path.resolve(cwd, appName);

  if (fs.existsSync(targetDirectory)) {
    return `Directory already exists: ${targetDirectory}`;
  }

  await fs.promises.mkdir(path.join(targetDirectory, "public"), {
    recursive: true,
  });
  await fs.promises.mkdir(path.join(targetDirectory, "routes"), {
    recursive: true,
  });
  await fs.promises.mkdir(path.join(targetDirectory, "views"), {
    recursive: true,
  });

  const files = buildExpressAppFiles(appName);

  for (const [relativePath, contents] of Object.entries(files)) {
    const destination = path.join(targetDirectory, relativePath);
    await fs.promises.writeFile(destination, contents, "utf8");
  }

  return [
    `Created Express app at ${targetDirectory}`,
    "Next steps:",
    `1. cd ${appName}`,
    "2. npm install",
    "3. npm start",
  ].join("\n");
}

async function runMigration({ cwd }) {
  const migrationsDirectory = path.resolve(cwd, "migrations");
  const dbPath = path.resolve(cwd, "els_memory.db");

  if (!fs.existsSync(migrationsDirectory)) {
    return `No migrations directory found at ${migrationsDirectory}. Create that folder and add .sql files.`;
  }

  const migrationFiles = (await fs.promises.readdir(migrationsDirectory))
    .filter((file) => file.toLowerCase().endsWith(".sql"))
    .sort((left, right) => left.localeCompare(right));

  if (migrationFiles.length === 0) {
    return `No .sql files found in ${migrationsDirectory}.`;
  }

  const db = await openDatabase(dbPath);

  try {
    await dbRun(
      db,
      `CREATE TABLE IF NOT EXISTS schema_migrations (
        id INTEGER PRIMARY KEY AUTOINCREMENT,
        name TEXT NOT NULL UNIQUE,
        applied_at DATETIME DEFAULT CURRENT_TIMESTAMP
      )`
    );

    const appliedRows = await dbAll(db, "SELECT name FROM schema_migrations");
    const appliedNames = new Set(appliedRows.map((row) => row.name));
    const executed = [];

    for (const fileName of migrationFiles) {
      if (appliedNames.has(fileName)) {
        continue;
      }

      const filePath = path.join(migrationsDirectory, fileName);
      const sql = await fs.promises.readFile(filePath, "utf8");

      if (!sql.trim()) {
        continue;
      }

      try {
        await dbExec(db, "BEGIN");
        await dbExec(db, sql);
        await dbRun(
          db,
          "INSERT INTO schema_migrations (name) VALUES (?)",
          [fileName]
        );
        await dbExec(db, "COMMIT");
        executed.push(fileName);
      } catch (error) {
        await dbExec(db, "ROLLBACK").catch(() => {});
        throw new Error(`Migration ${fileName} failed: ${error.message}`);
      }
    }

    if (executed.length === 0) {
      return `No pending migrations. Database is up to date at ${dbPath}.`;
    }

    return [
      `Applied ${executed.length} migration(s) to ${dbPath}:`,
      ...executed.map((fileName) => `- ${fileName}`),
    ].join("\n");
  } finally {
    await closeDatabase(db);
  }
}

async function deployLocal({ args, cwd }) {
  const scriptName = args.script || "start";
  const packageJsonPath = path.resolve(cwd, "package.json");

  if (!fs.existsSync(packageJsonPath)) {
    return `No package.json found at ${packageJsonPath}.`;
  }

  const packageJson = JSON.parse(
    await fs.promises.readFile(packageJsonPath, "utf8")
  );
  const scripts = packageJson.scripts || {};
  const scriptCommand = scripts[scriptName];

  if (!scriptCommand) {
    return `No npm script named "${scriptName}" was found in ${packageJsonPath}.`;
  }

  if (/cli[\\/]+index\.js/i.test(scriptCommand)) {
    return `The "${scriptName}" script launches the interactive CLI, so I did not background it. Try "deploy-local dashboard" or run "npm ${scriptName === "start" ? "start" : `run ${scriptName}`}" yourself.`;
  }

  const logsDirectory = path.resolve(cwd, "logs");
  await fs.promises.mkdir(logsDirectory, {
    recursive: true,
  });

  const logPath = path.join(logsDirectory, `${scriptName}.log`);
  const outputHandle = fs.openSync(logPath, "a");
  const command =
    process.platform === "win32"
      ? "cmd.exe"
      : process.env.SHELL || "/bin/sh";
  const commandArgs =
    process.platform === "win32"
      ? [
          "/c",
          scriptName === "start" ? "npm start" : `npm run ${scriptName}`,
        ]
      : [
          "-lc",
          scriptName === "start" ? "npm start" : `npm run ${scriptName}`,
        ];

  const child = spawn(command, commandArgs, {
    cwd,
    detached: true,
    stdio: ["ignore", outputHandle, outputHandle],
  });

  child.unref();

  const lines = [
    `Started npm script "${scriptName}" in the background.`,
    `PID: ${child.pid}`,
    `Log: ${logPath}`,
  ];

  if (scriptName === "dashboard") {
    lines.push("Dashboard: http://localhost:3001");
  }

  return lines.join("\n");
}

module.exports = {
  "create-express-app": createExpressApp,
  "deploy-local": deployLocal,
  "run-migration": runMigration,
};
